makefile
#Makefile
        #Specify the compiler
CC=gcc
                 #Specify compiler flags
CFLAGS=-I.
                #Specify the target and dependencies
hellomake: hellomake.c hellofunc.c
	$(CC) -o hellomake hellomake.c hellofunc.c $(CFLAGS)
